name: Feature request
description: Propose an enhancement
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
